apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-daemonset
  labels:
    app: multitool
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: varlog
              mountPath: /var/log/syslog
              readOnly: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/syslog
            type: File
