apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: netology-1.2
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
