apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
      name: http-nginx
    - port: 1180
      nodePort: 30002
      protocol: TCP
      name: http-multitool
