---
- name: Will wait till reachable
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for hosts available
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 120
    - name: Gather facts for the first time
      ansible.builtin.setup:
  tags: wait, all-hosts

- name: Clickhouse
  hosts: clickhouse
  tags: clickhouse
  roles:
    - role: clickhouse
  post_tasks:
    - name: Create clickhouse table
      ansible.builtin.command:
        cmd: "clickhouse-client --query 'CREATE TABLE IF NOT EXISTS {{ clickhouse_db }}.{{ table }} {{ table_create_config }};'"
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc != 57
      changed_when: create_table.rc == 0

- name: Vector
  hosts: vector
  vars_files: group_vars/clickhouse.yml
  tags: vector
  roles:
    - role: vector-role

- name: Lighthouse+Nginx
  tags: nginx, lighthouse
  hosts: lighthouse
  vars_files: group_vars/clickhouse.yml
  become: true
  roles:
    - role: lighthouse-role
