---
- name: Will wait till reachable
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Wait for
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
    - name: Gather facts for the first time
      ansible.builtin.setup:

- name: test
  gather_facts: false
  hosts: all
  vars:
    ansible_user: ubuntu
  become: yes
  tasks:
  
  - name: Install Nginx Web Server on Debian Family
    apt:
      name: nginx
      state: latest   
      update_cache: yes 
    