galaxy_info:
  role_name: vector_role
  author: Nikita Bulgakov
  description: This role for install Vector on EL
  company: Netology

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: CentOS
      versions:
        - 7
        - 8
    - name: RHEL
      versions:
        - 7
        - 8

  galaxy_tags:
    - vector

dependencies: []
