---
- name: Will wait till reachable
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for hosts available
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 120
    - name: Gather facts for the first time
      ansible.builtin.setup:
  tags: wait, all-hosts

- name: Clickhouse
  hosts: clickhouse
  tags: clickhouse
  roles:
    - role: Clickhouse

- name: Vector
  hosts: vector
  vars_files: group_vars/clickhouse/clickhouse.yml
  tags: vector
  roles:
    - role: Vector

- name: Lighthouse+Nginx
  tags: nginx, lighthouse
  hosts: lighthouse
  vars_files: group_vars/clickhouse/clickhouse.yml
  become: true
  roles:
    - role: Lighthouse
