apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment
  labels:
    app: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-pvc
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: data
              mountPath: /rw
