apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multibox-pvc
  namespace: multibox
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: multibox-pv
