---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 62.84.127.196
      ansible_user: clickhouse
      ansible_connection: ssh
vector:
  hosts:
    vector-01:
      ansible_host: 51.250.6.53
      ansible_user: vector
      ansible_connection: ssh
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 62.84.127.111
      ansible_user: lighthouse
      ansible_connection: ssh
