---
clickhouse_version: "22.3.3.44"
clickhouse_users_custom:
  - name: logger
    password: logger
    networks: "{{ clickhouse_networks_default }}"
    profile: "default"
    quota: "default"
    dbs: ["logs"]
clickhouse_networks_default:
  - "::/0"
  - "127.0.0.1"
clickhouse_profiles_default:
  default:
    max_memory_usage: 10000000000
    use_uncompressed_cache: 0
    load_balancing: random
    date_time_input_format: best_effort
    max_partitions_per_insert_block: 100
clickhouse_dbs_custom:
  - { name: logs }
clickhouse_listen_host:
  - "::"
clickhouse_http_port: 8123
table: "some_log"
table_engine: "Log"
table_create_config: "('file' String, 'hosts' String, 'message' String, 'timestamp' DateTime) Engine={{ table_engine }}"
