---
- name: Create logs directory
  ansible.builtin.file:
    path: "{{ vector_logs_path }}"
    state: directory
    mode: '0755'
- name: Create log file
  ansible.builtin.lineinfile:
    create: true
    path: "{{ vector_logs_path }}/someone.log"
    line: "[ERROR] Some log with trace"
    mode: "0664"
- name: Ensure vector directory exists
  ansible.builtin.file:
    path: "{{ vector_path }}"
    state: directory
    mode: "0755"
- name: Install Vector
  become: true
  ansible.builtin.yum:
    name:
      - https://yum.vector.dev/stable/vector-0/{{ vector_arch }}/vector-{{ vector_version }}-1.{{ vector_arch }}.rpm
- name: Configure Vector | Ensure config directory exists
  ansible.builtin.file:
    path: "{{ vector_config_path }}"
    state: directory
    mode: "0755"
- name: Configure Vector | Template config
  ansible.builtin.template:
    src: vector.yml.j2
    mode: "0644"
    dest: "{{ vector_config_path }}/vector.yaml"
- name: Configure Service | Template systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"
  notify: Start Vector service
